// Generated by CoffeeScript 1.6.2
(function() {
  var http, server;

  http = require('http');

  server = http.createServer(function(req, res) {
    res.end('yo');
    debugger;
  });

  server.listen(9000);

}).call(this);

/*
//@ sourceMappingURL=app.map
*/
